# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

#
# User specific aliases and functions
#
alias em='emacs -nw'
alias ls='ls -v --group-directories-first --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias top='top -e m -E m'
alias wget='wget --no-hsts'
alias open='xdg-open'
alias sudo='sudo '
alias birthday="stat / | grep \"Birth\" | sed 's/Birth: //g' | cut -b 2-11"

# Change between dark mode and light mode quickly
alias lt="gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' && gsettings set org.gnome.desktop.interface color-scheme 'default'"
alias dt="gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"

bind -f $HOME/.config/inputrc
shopt -s checkwinsize
