# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
export LESSHISTFILE=/dev/null
export LC_TIME=en_GB.UTF-8
